image: node:latest

build:
  stage: build
  script:
    - rm -rf ./frontend_build.zip
    - npm install
    - cd yourdoc_frontend
    - rm -rf build
    - npm install
    - npm run build
    - cd ..
    - cd yourdoc_backend
    - npm install
  environment: production
  only:
    - main

test:
  stage: test
  script:
    - cd yourdoc_backend
    - npm run test
  only:
    - main

deploy:
  stage: deploy
  script:
    - bash deploy.sh
  environment: production
  only:
    - main
